# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  create-coverage-report:
    docker:
      - image: cimg/node:16.19.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: "Run tests for changed files and create coverage html report"
          command: |
            npm run test:coverage
      - run:
          name: "Update PR with the coverage report"
          command: |
            output=$(.circleci/helpers/create_fe_test_coverage_report.sh 2>&1)
            echo "$output"
          when: always
      - store_artifacts:
          path: coverage

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-coverage-workflow:
    jobs:
      - create-coverage-report
